# Generated by Django 6.0.1 on 2026-02-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complexe', models.CharField(default='COMPLEXE HOTELIER BEHANIAN', max_length=255)),
                ('adresse', models.CharField(default='Yopougon Beago à 2000m du Palais de justice', max_length=255)),
                ('telephone1', models.CharField(default='07 58 29 11 10', max_length=20)),
                ('telephone2', models.CharField(blank=True, default='01 43 09 76 16', max_length=20)),
                ('email', models.EmailField(default='complexebehanian@gmail.com', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('slogan', models.CharField(blank=True, default='Votre confort, notre priorité', max_length=255)),
            ],
            options={
                'verbose_name': 'Coordonnées du Complexe',
                'verbose_name_plural': 'Coordonnées du Complexe',
            },
        ),
    ]
