# Generated by Django 6.0.1 on 2026-02-18 20:14

from django.db import migrations

def create_coordonnees(apps, schema_editor):
    Coordonnees = apps.get_model('parametres', 'Coordonnees')
    if not Coordonnees.objects.exists():
        Coordonnees.objects.create()

def delete_coordonnees(apps, schema_editor):
    Coordonnees = apps.get_model('parametres', 'Coordonnees')
    Coordonnees.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_coordonnees, delete_coordonnees),
    ]
