# Generated by Django 5.2 on 2026-09-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_operateurmobilemoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('poste', models.CharField(blank=True, max_length=100, verbose_name='Poste / Fonction')),
                ('salaire_base', models.PositiveIntegerField(default=0, verbose_name='Salaire mensuel (FCFA)')),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour retirer de la liste de paiement', verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés (RH)',
                'ordering': ['nom_complet'],
            },
        ),
    ]
