# Generated by Django 5.2 on 2026-09-18 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0015_salaire_config'),
        ('parametres', '0004_employe_rh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaireConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_base', models.PositiveIntegerField(default=0, verbose_name='Salaire mensuel (FCFA)')),
                ('actif_paie', models.BooleanField(default=True, help_text='Décocher pour exclure de la liste de paiement coffre', verbose_name='Actif en paie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salaire_config', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Salaire employé',
                'verbose_name_plural': 'Salaires employés (RH)',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
