# Generated by Django 6.0.1 on 2026-02-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complexe', models.CharField(default='Votre Complexe Hôtelier', max_length=255)),
                ('adresse', models.TextField(blank=True, help_text="Adresse complète de l'établissement")),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('notes_pied_de_page', models.TextField(blank=True, help_text='Informations légales ou autres notes à afficher en bas des documents')),
            ],
            options={
                'verbose_name': 'Configuration du Complexe',
                'verbose_name_plural': 'Configuration du Complexe',
            },
        ),
    ]
