# Generated by Django 5.0.4 on 2026-02-17 18:24

from django.db import migrations


def update_complexe_details(apps, schema_editor):
    """Met à jour les informations du complexe avec les valeurs réelles."""
    Configuration = apps.get_model('dashboard', 'Configuration')
    # Utilise get_or_create pour être sûr qu'un objet existe
    config, created = Configuration.objects.get_or_create(pk=1)

    config.nom_complexe = "COMPLEXE HOTELIER BEHANIAN"
    config.adresse = "Yopougon Beago à 2000m du Palais de justice"
    config.telephone = "07 58 29 11 10 / 01 43 09 76 16"
    config.email = "complexebehanian@gmail.com"
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_complexe_details),
    ]
