# Generated by Django 6.0.1 on 2026-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_update_complexe_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='adresse',
            field=models.TextField(blank=True, default='Yopougon Beago à 2000m du Palais de justice'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='email',
            field=models.EmailField(blank=True, default='complexebehanian@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='nom_complexe',
            field=models.CharField(default='COMPLEXE HOTELIER BEHANIAN', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='telephone',
            field=models.CharField(blank=True, default='07 58 29 11 10 / 01 43 09 76 16', max_length=100),
        ),
    ]
