# Generated by Django 6.0.2 on 2026-05-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_configuration_adresse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('type_reset', models.CharField(choices=[('partiel', 'Remise Partielle'), ('complet', 'Remise Totale'), ('personnalise', 'Remise Personnalisée')], max_length=20, verbose_name='Type')),
                ('modules', models.JSONField(default=dict, verbose_name='Modules supprimés')),
                ('counts_avant', models.JSONField(default=dict, verbose_name='Comptages avant reset')),
                ('backup_path', models.CharField(blank=True, max_length=500, verbose_name='Fichier backup')),
                ('succes', models.BooleanField(default=True, verbose_name='Succès')),
                ('erreur', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Exécuté par')),
            ],
            options={
                'verbose_name': 'Journal de remise à zéro',
                'verbose_name_plural': 'Journal des remises à zéro',
                'ordering': ['-date'],
            },
        ),
    ]
