# Generated by Django 6.0.1 on 2026-02-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_platmenu_image_alter_commande_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('client_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_reservation', models.DateTimeField(verbose_name='Date et heure')),
                ('nombre_personnes', models.IntegerField(verbose_name='Nombre de personnes')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='confirmee', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['date_reservation'],
            },
        ),
    ]
