# Generated by Django 6.0.1 on 2026-02-13 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='accompagnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_accompagnement', to='restaurant.platmenu', verbose_name='Accompagnement'),
        ),
    ]
