# Generated by Django 6.0.1 on 2026-02-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_lignecommande_accompagnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='platmenu',
            name='is_accompagnement',
            field=models.BooleanField(default=False, verbose_name='Est un accompagnement'),
        ),
    ]
