# Generated by Django 6.0.2 on 2026-03-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_platmenu_is_accompagnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platmenu',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix (FCFA)'),
        ),
    ]
