# Generated by Django 6.0.3 on 2026-03-16 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_cassebar_lignecassebar'),
        ('restaurant', '0006_alter_platmenu_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='boisson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='bar.boissonbar', verbose_name='Boisson'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='nom_article',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom article'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='plat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.platmenu', verbose_name='Plat'),
        ),
    ]
