# Generated by Django 6.0.2 on 2026-04-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_cassebar_lignecassebar'),
        ('cuisine', '0002_categorieplat_uniteingredient_and_more'),
        ('restaurant', '0007_add_boisson_to_lignecommande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du forfait')),
                ('module', models.CharField(choices=[('piscine', 'Piscine'), ('espaces', 'Espaces Événementiels'), ('hotel', 'Hôtel'), ('restaurant', 'Restaurant'), ('autre', 'Autre')], default='piscine', max_length=20, verbose_name='Module concerné')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix forfait (FCFA)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('image', models.ImageField(blank=True, null=True, upload_to='forfaits/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Forfait',
                'verbose_name_plural': 'Forfaits',
                'ordering': ['module', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneForfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_item', models.CharField(choices=[('plat', 'Plat cuisine'), ('boisson', 'Boisson cave'), ('autre', 'Autre prestation')], default='plat', max_length=10)),
                ('libelle', models.CharField(blank=True, max_length=200, verbose_name='Libellé libre (si pas plat/boisson)')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('boisson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forfaits', to='bar.boissonbar')),
                ('forfait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='restaurant.forfait')),
                ('plat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forfaits', to='cuisine.plat')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
