# Generated by Django 6.0.2 on 2026-04-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_forfait_ligneforfait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneforfait',
            name='forfait',
        ),
        migrations.RemoveField(
            model_name='ligneforfait',
            name='boisson',
        ),
        migrations.RemoveField(
            model_name='ligneforfait',
            name='plat',
        ),
        migrations.DeleteModel(
            name='Forfait',
        ),
        migrations.DeleteModel(
            name='LigneForfait',
        ),
    ]
