# Generated by Django 6.0.2 on 2026-04-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_forfait_ligneforfait'),
    ]

    operations = [
        migrations.AddField(
            model_name='platmenu',
            name='cuisine_plat_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID du plat Cuisine source — synchro permanente par ID', null=True),
        ),
    ]
