# Generated by Django 6.0.2 on 2026-04-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_platmenu_cuisine_plat_id'),
        ('restaurant', '0010_platmenu_cuisine_plat_id'),
    ]

    operations = [
    ]
