# Generated by Django 6.0.2 on 2026-05-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_ligneforfait_forfait_and_more'),
        ('restaurant', '0011_merge_20260402_1315'),
    ]

    operations = [
    ]
