# Generated by Django 6.0.2 on 2026-05-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_merge_20260504_1121'),
        ('restaurant', '0013_forfait_ligneforfait'),
    ]

    operations = [
    ]
