# Generated by Django 6.0.2 on 2026-05-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_merge_20260504_1131'),
        ('restaurant', '0014_souscriptionforfait'),
    ]

    operations = [
    ]
