# Generated by Django 5.2 on 2026-05-21 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0012_alter_avoir_statut_alter_facture_statut_and_more'),
        ('restaurant', '0015_merge_20260516_0909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscriptionforfait',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='forfait',
            name='module',
            field=models.CharField(choices=[('piscine', 'Piscine'), ('hotel', 'Hôtel'), ('restaurant', 'Restaurant'), ('bar', 'Bar / Cave'), ('espaces', 'Espaces Événementiels'), ('caisse', 'Caisse / Accueil'), ('autre', 'Autre')], default='piscine', max_length=20, verbose_name='Module concerné'),
        ),
        migrations.AlterField(
            model_name='souscriptionforfait',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souscriptions', to='facturation.client', verbose_name='Client enregistré'),
        ),
        migrations.AlterField(
            model_name='souscriptionforfait',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souscriptions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='souscriptionforfait',
            name='date_validite',
            field=models.DateField(blank=True, null=True, verbose_name='Date de validité'),
        ),
        migrations.AlterField(
            model_name='souscriptionforfait',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('carte_bancaire', 'Carte bancaire'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('autre', 'Autre')], default='especes', max_length=30, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='souscriptionforfait',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant encaissé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='souscriptionforfait',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AlterField(
            model_name='souscriptionforfait',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence (chambre, table…)'),
        ),
        migrations.AlterField(
            model_name='souscriptionforfait',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('consommee', 'Consommée'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='active', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='souscriptionforfait',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souscription', to='facturation.ticket', verbose_name='Ticket de caisse'),
        ),
    ]
