# Generated by Django 5.2 on 2026-06-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_remove_souscriptionforfait_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nb_couverts',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de couverts'),
        ),
        migrations.AddField(
            model_name='commande',
            name='remise_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Note / instructions'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total brut (FCFA)'),
        ),
    ]
