# Generated by Django 5.2 on 2026-06-29 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_sprint1_note_remise_couverts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='caissier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaissements', to=settings.AUTH_USER_MODEL, verbose_name='Caissier (encaissement)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='montant_rendu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant rendu (FCFA)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero_fiscal',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N° fiscal (CMD-YYYY-XXXX)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='serveur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_serveur', to=settings.AUTH_USER_MODEL, verbose_name='Serveur'),
        ),
    ]
