# Generated by Django 5.2 on 2026-07-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_sprint2_numero_fiscal_rendu_caissier'),
    ]

    operations = [
        migrations.AddField(
            model_name='platmenu',
            name='is_simple',
            field=models.BooleanField(default=False, verbose_name='Plat simple (sans stock)'),
        ),
    ]
