# Generated by Django 5.2 on 2026-07-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_add_is_simple_to_platmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriemenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='restaurant.categoriemenu', verbose_name='Catégorie parente'),
        ),
    ]
