# Generated by Django 5.2 on 2026-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_table_salon_prive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='montant_rendu',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Montant rendu (FCFA)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='remise_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Total brut (FCFA)'),
        ),
        migrations.AlterField(
            model_name='forfait',
            name='prix',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix forfait (FCFA)'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='platmenu',
            name='prix',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='souscriptionforfait',
            name='montant_paye',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Montant encaissé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='tarif_horaire',
            field=models.DecimalField(decimal_places=3, default=5000, max_digits=10, verbose_name='Tarif horaire (F)'),
        ),
    ]
