# Generated by Django 6.0.2 on 2026-03-29 20:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caissesession',
            options={'ordering': ['-opened_at']},
        ),
        migrations.AddField(
            model_name='caissesession',
            name='fond_caisse',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='fond_caisse_reel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fond compté à la clôture', max_digits=12),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='prelevement_banque',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='total_carte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='total_especes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='total_general',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='total_mobile',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='total_virement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='caissesession',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('encaissement', 'Encaissement'), ('versement', 'Versement module → Caisse'), ('prelevement', 'Prélèvement banque'), ('depense', 'Dépense / Décaissement'), ('remboursement', 'Remboursement client'), ('ajustement', 'Ajustement caisse'), ('fond_caisse', 'Fond de caisse')], max_length=20)),
                ('module', models.CharField(choices=[('hotel', 'Hôtel'), ('restaurant', 'Restaurant'), ('cave', 'Cave / Bar'), ('piscine', 'Piscine'), ('espaces', 'Espaces Événementiels'), ('caisse', 'Caisse'), ('banque', 'Banque'), ('autre', 'Autre')], default='caisse', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('carte_bancaire', 'Carte Bancaire'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('autre', 'Autre')], default='especes', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('reference', models.CharField(blank=True, help_text='N° ticket, facture, bon…', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valide', models.BooleanField(default=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_caisse', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='caisse.caissesession')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PrelevementBanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('banque', models.CharField(blank=True, help_text='Nom de la banque', max_length=100)),
                ('reference', models.CharField(blank=True, help_text='N° bordereau', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prelevements', to='caisse.caissesession')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
