# Generated by Django 6.0.2 on 2026-03-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_alter_caissesession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caissesession',
            name='type_caisse',
            field=models.CharField(choices=[('hotel', 'Caisse Hôtel (Réception)'), ('module', 'Caisse Module (Restaurant/Cave/Piscine/Espaces)'), ('centrale', 'Caisse Centrale (Manager)')], default='module', max_length=20),
        ),
    ]
