# Generated by Django 6.0.2 on 2026-04-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_caissesession_type_caisse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissesession',
            name='type_caisse',
            field=models.CharField(choices=[('hotel', 'Caisse Hôtel (Réception)'), ('module', 'Caisse Module (Restaurant/Cave/Piscine/Espaces)'), ('centrale', 'Caisse Centrale (Caissière Principale)')], default='module', max_length=20),
        ),
    ]
