# Generated by Django 5.2 on 2026-05-21 11:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0005_caissesession_journalier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissesession',
            name='fond_caisse_reel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fond compté physiquement à la clôture', max_digits=12),
        ),
    ]
