# Generated by Django 5.2 on 2026-09-01 12:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0006_alter_caissesession_fond_caisse_reel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissesession',
            name='ecart',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Écart = Solde théorique − Fond réel compté (négatif = manquant)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='caissesession',
            name='fond_caisse',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='caissesession',
            name='fond_caisse_reel',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Fond compté physiquement à la clôture', max_digits=12),
        ),
        migrations.AlterField(
            model_name='caissesession',
            name='prelevement_banque',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='caissesession',
            name='solde_theorique',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Fond initial + espèces encaissées − prélèvements banque', max_digits=12),
        ),
        migrations.AlterField(
            model_name='caissesession',
            name='total_carte',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='caissesession',
            name='total_especes',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='caissesession',
            name='total_general',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='caissesession',
            name='total_mobile',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='caissesession',
            name='total_virement',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='montant',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='prelevementbanque',
            name='montant',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
