# Generated by Django 5.2 on 2026-09-05 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0007_alter_caissesession_ecart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caissesession',
            name='reouverture_autorisee',
            field=models.BooleanField(default=False, help_text="Un manager a autorisé la réouverture d'une session après clôture pour ce jour."),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='reouverture_par',
            field=models.ForeignKey(blank=True, help_text="Manager ayant accordé l'autorisation de réouverture.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reouvertures_autorisees', to=settings.AUTH_USER_MODEL),
        ),
    ]
