# Generated by Django 5.2 on 2026-09-06 19:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0008_caissesession_reouverture_autorisee'),
    ]

    operations = [
        migrations.AddField(
            model_name='caissesession',
            name='declared_moov',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='declared_mtn',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='declared_orange',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='declared_wave',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
    ]
