# Generated by Django 5.2 on 2026-09-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0009_caisse_declared_mobile_per_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='caissesession',
            name='billetage_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
