# Generated by Django 5.2 on 2026-09-13 19:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0010_caisse_billetage_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_caisse', models.CharField(choices=[('centrale', 'Caisse Centrale'), ('hotel', 'Caisse Hôtel'), ('module', 'Caisse Module')], max_length=20, unique=True)),
                ('fond_fixe', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Fond fixe remis au shift suivant (0 = aucun fond fixe, caissière démarre à zéro)', max_digits=12)),
            ],
            options={
                'verbose_name': 'Configuration de caisse',
                'verbose_name_plural': 'Configurations de caisse',
            },
        ),
        migrations.AddField(
            model_name='caissesession',
            name='fond_fixe_applique',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text="Fond fixe configuré au moment de l'ouverture — remis au shift suivant.", max_digits=12),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Verrouillée : plus aucune transaction enregistrable sur cette session.'),
        ),
        migrations.AddField(
            model_name='caissesession',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage du verrouillage (début du comptage physique).', null=True),
        ),
    ]
