# Generated by Django 5.2 on 2026-09-18 00:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0011_caisse_config_et_verrouillage_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemiseSoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('montant_recu', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Espèces reçues de la caissière (= fond_caisse_reel de la clôture)', max_digits=12)),
                ('montant_banque', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Montant versé à la banque', max_digits=12)),
                ('montant_coffre', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Montant gardé en coffre direction (calculé = recu − banque)', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remises_soir_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='Session centrale clôturée correspondante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remises_soir', to='caisse.caissesession')),
            ],
            options={
                'verbose_name': 'Remise soir (coffre)',
                'verbose_name_plural': 'Remises soir (coffre)',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
