# Generated by Django 5.2 on 2026-09-18 00:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0012_remise_soir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('poste', models.CharField(blank=True, max_length=100)),
                ('salaire_base', models.PositiveIntegerField(default=0, help_text='Salaire mensuel configuré en FCFA')),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='MouvementCoffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('type', models.CharField(choices=[('remise_caisse', '💵 Remise caissière → Coffre'), ('prelevement_direction', '👤 Prélèvement Direction'), ('salaire', '👷 Paiement Salaire'), ('facture_cie', '💡 Facture CIE (Électricité)'), ('facture_sodeci', '🚰 Facture SODECI (Eau)'), ('facture_internet', '🌐 Facture Internet'), ('travaux', '🔧 Travaux / Entretien'), ('divers', '📦 Dépense Diverse')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('montant_recu', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Espèces totales reçues de la caissière', max_digits=12)),
                ('montant_banque', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Part immédiatement déposée en banque', max_digits=12)),
                ('fournisseur', models.CharField(blank=True, help_text='Prestataire, banque, bénéficiaire…', max_length=200)),
                ('reference', models.CharField(blank=True, help_text='N° facture, bordereau, reçu…', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_salaire', to='caisse.employe')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_coffre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement coffre',
                'verbose_name_plural': 'Mouvements coffre',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RemiseSoir',
        ),
    ]
