# Generated by Django 5.2 on 2026-09-18 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0013_employe_mouvementcoffre'),
        ('parametres', '0004_employe_rh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementcoffre',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_salaire', to='parametres.employe'),
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
