# Generated by Django 5.2 on 2026-09-18 01:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0016_mouvementcoffre_versement_banque'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcoffre',
            name='session_source',
            field=models.ForeignKey(blank=True, help_text='Session clôturée ayant généré cette reddition automatiquement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redditions_coffre', to='caisse.caissesession'),
        ),
        migrations.AlterField(
            model_name='mouvementcoffre',
            name='montant_banque',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Réservé (non utilisé)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='mouvementcoffre',
            name='type',
            field=models.CharField(choices=[('remise_caisse', '💰 Reddition de caisse → Coffre'), ('versement_banque', '🏛️ Versement en Banque'), ('prelevement_direction', '👤 Prélèvement Direction'), ('salaire', '👷 Paiement Salaire'), ('facture_cie', '💡 Facture CIE (Électricité)'), ('facture_sodeci', '🚰 Facture SODECI (Eau)'), ('facture_internet', '🌐 Facture Internet'), ('travaux', '🔧 Travaux / Entretien'), ('divers', '📦 Dépense Diverse')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mouvementcoffre',
            name='valide',
            field=models.BooleanField(default=True, help_text='False = en attente de validation manager (reddition auto)'),
        ),
    ]
