# Generated by Django 5.2 on 2026-09-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0017_mouvementcoffre_session_source_reddition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementcoffre',
            name='type',
            field=models.CharField(choices=[('remise_caisse', '💰 Dépôt en coffre'), ('versement_banque', '🏛️ Versement en Banque'), ('prelevement_direction', '👤 Prélèvement Direction'), ('salaire', '👷 Paiement Salaire'), ('facture_cie', '💡 Facture CIE (Électricité)'), ('facture_sodeci', '🚰 Facture SODECI (Eau)'), ('facture_internet', '🌐 Facture Internet'), ('travaux', '🔧 Travaux / Entretien'), ('divers', '📦 Dépense Diverse')], max_length=30),
        ),
    ]
