# Generated by Django 6.0.1 on 2026-01-22 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspaceEvenementiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'espace")),
                ('type_espace', models.CharField(choices=[('salle_conference', 'Salle de conférence'), ('salle_reception', 'Salle de réception'), ('espace_exterieur', 'Espace extérieur'), ('jardin', 'Jardin'), ('terrasse', 'Terrasse')], max_length=50, verbose_name='Type')),
                ('capacite', models.IntegerField(verbose_name='Capacité (personnes)')),
                ('prix_heure', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par heure (FCFA)')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie (m²)')),
                ('projecteur', models.BooleanField(default=False, verbose_name='Projecteur')),
                ('wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('climatisation', models.BooleanField(default=False, verbose_name='Climatisation')),
                ('sonorisation', models.BooleanField(default=False, verbose_name='Sonorisation')),
                ('decoration', models.BooleanField(default=False, verbose_name='Décoration')),
                ('eclairage', models.BooleanField(default=False, verbose_name='Éclairage')),
                ('tentes', models.BooleanField(default=False, verbose_name='Tentes')),
                ('parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reservee', 'Réservée'), ('occupee', 'Occupée')], default='disponible', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Espace événementiel',
                'verbose_name_plural': 'Espaces Location',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], max_length=20, verbose_name='Type de client')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('type_evenement', models.CharField(max_length=100, verbose_name="Type d'événement")),
                ('date_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('nombre_personnes', models.IntegerField(verbose_name='Nombre de personnes')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total (FCFA)')),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise (FCFA)')),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Avance payée (FCFA)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espaces_evenementiels.espaceevenementiel', verbose_name='Espace')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_debut'],
            },
        ),
    ]
