# Generated by Django 6.0.1 on 2026-01-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_evenementiels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espaceevenementiel',
            options={'ordering': ['nom'], 'verbose_name': 'Espace Location', 'verbose_name_plural': 'Espaces Location'},
        ),
    ]
