# Generated by Django 6.0.2 on 2026-03-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_evenementiels', '0002_alter_espaceevenementiel_options'),
        ('hotel', '0002_add_piscine_type_consommation'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaceevenementiel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='espaces/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='reservationespace',
            name='reservation_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_espace', to='hotel.reservation', verbose_name='Réservation hôtel'),
        ),
        migrations.AlterField(
            model_name='reservationespace',
            name='type_client',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('heberge', 'Résident hôtel')], max_length=20, verbose_name='Type de client'),
        ),
    ]
