# Generated by Django 6.0.2 on 2026-03-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_evenementiels', '0003_espaceevenementiel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espaceevenementiel',
            name='prix_heure',
        ),
        migrations.AddField(
            model_name='espaceevenementiel',
            name='prix_jour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix par jour (FCFA)'),
        ),
    ]
