# Generated by Django 6.0.2 on 2026-03-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_evenementiels', '0004_remove_espaceevenementiel_prix_heure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaceevenementiel',
            name='prix_demi_journee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Prix demi-journée (FCFA)'),
        ),
        migrations.AddField(
            model_name='reservationespace',
            name='type_duree',
            field=models.CharField(choices=[('journee', 'Journée complète'), ('demi_matin', 'Demi-journée matin (8h-13h)'), ('demi_aprem', 'Demi-journée après-midi (14h-18h)')], default='journee', max_length=20, verbose_name='Type de durée'),
        ),
    ]
