# Generated by Django 6.0.2 on 2026-03-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_evenementiels', '0005_espaceevenementiel_prix_demi_journee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaceevenementiel',
            name='prix_demi_journee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Prix demi-journée (FCFA)'),
        ),
    ]
