# Generated by Django 6.0.2 on 2026-03-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_evenementiels', '0006_alter_espaceevenementiel_prix_demi_journee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationespace',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mode de paiement'),
        ),
    ]
