# Generated by Django 6.0.2 on 2026-03-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_evenementiels', '0007_reservationespace_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationespace',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True, verbose_name="Motif d'annulation"),
        ),
        migrations.AddField(
            model_name='reservationespace',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° Réservation'),
        ),
    ]
