# Generated by Django 6.0.2 on 2026-03-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_evenementiels', '0008_reservationespace_motif_annulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationespace',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N° Réservation'),
        ),
    ]
