# Generated by Django 5.2 on 2026-07-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_evenementiels', '0009_alter_reservationespace_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaceevenementiel',
            name='type_espace',
            field=models.CharField(choices=[('salle_conference', 'Salle de conférence'), ('salle_reception', 'Salle de réception'), ('espace_exterieur', 'Espace extérieur'), ('jardin', 'Jardin'), ('terrasse', 'Terrasse'), ('restauration', 'Restauration')], max_length=50, verbose_name='Type'),
        ),
    ]
