# Generated by Django 5.2 on 2026-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_evenementiels', '0010_alter_espaceevenementiel_type_espace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaceevenementiel',
            name='prix_demi_journee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Prix demi-journée (FCFA)'),
        ),
        migrations.AlterField(
            model_name='espaceevenementiel',
            name='prix_jour',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Prix par jour (FCFA)'),
        ),
        migrations.AlterField(
            model_name='espaceevenementiel',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Superficie (m²)'),
        ),
        migrations.AlterField(
            model_name='reservationespace',
            name='avance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Avance payée (FCFA)'),
        ),
        migrations.AlterField(
            model_name='reservationespace',
            name='prix_total',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix total (FCFA)'),
        ),
        migrations.AlterField(
            model_name='reservationespace',
            name='remise',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Remise (FCFA)'),
        ),
    ]
