# Generated by Django 6.0.2 on 2026-03-11 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bar', '0002_initial'),
        ('espaces_evenementiels', '0002_alter_espaceevenementiel_options'),
        ('restaurant', '0006_alter_platmenu_prix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Numéro')),
                ('type_chambre', models.CharField(choices=[('standard', 'Standard'), ('superieure', 'Supérieure'), ('suite', 'Suite'), ('vip', 'VIP')], max_length=20, verbose_name='Type')),
                ('etage', models.IntegerField(verbose_name='Étage')),
                ('capacite', models.IntegerField(default=2, verbose_name='Capacité (personnes)')),
                ('prix_nuit', models.IntegerField(verbose_name='Prix Nuitée (FCFA)')),
                ('prix_sejour', models.IntegerField(default=0, verbose_name='Prix Séjour (FCFA)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupee', 'Occupée'), ('maintenance', 'Maintenance'), ('reservation', 'Réservation')], default='disponible', max_length=20, verbose_name='Statut')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chambres/', verbose_name='Photo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('wifi', models.BooleanField(default=True, verbose_name='WiFi')),
                ('climatisation', models.BooleanField(default=True, verbose_name='Climatisation')),
                ('television', models.BooleanField(default=True, verbose_name='Télévision')),
                ('minibar', models.BooleanField(default=False, verbose_name='Minibar')),
                ('machine_a_cafe', models.BooleanField(default=False, verbose_name='Machine à café')),
                ('baignoire', models.BooleanField(default=False, verbose_name='Baignoire')),
                ('coffre_fort', models.BooleanField(default=False, verbose_name='Coffre-fort')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('piece_identite', models.CharField(blank=True, max_length=50, null=True, verbose_name="Pièce d'identité")),
                ('numero_piece', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de pièce')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('nationalite', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationalité')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateField(verbose_name="Date d'arrivée")),
                ('date_depart', models.DateField(verbose_name='Date de départ')),
                ('type_sejour', models.CharField(choices=[('nuitee', 'Nuitée'), ('long_sejour', 'Long Séjour')], default='nuitee', max_length=20, verbose_name='Type de Séjour')),
                ('nombre_adultes', models.IntegerField(default=1, verbose_name='Adultes')),
                ('nombre_enfants', models.IntegerField(default=0, verbose_name='Enfants')),
                ('provenance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provenance')),
                ('destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destination')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('prix_total', models.IntegerField(verbose_name='Prix total (FCFA)')),
                ('avance', models.IntegerField(default=0, verbose_name='Avance payée (FCFA)')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('carte', 'Carte Bancaire'), ('virement', 'Virement'), ('cheque', 'Chèque')], default='especes', max_length=20, verbose_name='Mode de Paiement')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.chambre', verbose_name='Chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.client', verbose_name='Client')),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(choices=[('bar', 'Bar'), ('restaurant', 'Restaurant'), ('espace', 'Espace Location'), ('autre', 'Autre Service')], max_length=20)),
                ('nom', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('boisson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.boissonbar')),
                ('espace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='espaces_evenementiels.espaceevenementiel')),
                ('plat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.platmenu')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='hotel.reservation')),
            ],
            options={
                'verbose_name': 'Consommation',
                'verbose_name_plural': 'Consommations',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
