# Generated by Django 6.0.2 on 2026-03-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='type_service',
            field=models.CharField(choices=[('bar', 'Bar'), ('restaurant', 'Restaurant'), ('espace', 'Espace Location'), ('piscine', 'Piscine'), ('autre', 'Autre Service')], max_length=20),
        ),
    ]
