# Generated by Django 5.2 on 2026-06-21 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_add_piscine_type_consommation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='serveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consommations_hotel', to=settings.AUTH_USER_MODEL, verbose_name='Serveur/Serveuse'),
        ),
    ]
