# Generated by Django 5.2 on 2026-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_reservation_heures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='prix_nuit',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix Repos 4h (FCFA)'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='prix_nuitee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Prix Nuitée 24h (FCFA)'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='prix_sejour',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Prix Journée 10h (FCFA)'),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='avance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Avance payée (FCFA)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix total (FCFA)'),
        ),
    ]
