# Generated by Django 5.2 on 2026-09-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_chambre_prix_nuit_alter_chambre_prix_nuitee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='remise',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Remise (FCFA)'),
        ),
    ]
