# Generated by Django 6.0.1 on 2026-01-21 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifPiscine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.CharField(choices=[('heberge', 'Hébergé'), ('visiteur', 'Visiteur')], max_length=20, unique=True, verbose_name='Type de client')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par personne (FCFA)')),
            ],
            options={
                'verbose_name': 'Tarif piscine',
                'verbose_name_plural': 'Tarifs piscine',
            },
        ),
        migrations.CreateModel(
            name='AccesPiscine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('type_client', models.CharField(choices=[('heberge', 'Hébergé'), ('visiteur', 'Visiteur')], max_length=20, verbose_name='Type')),
                ('nombre_personnes', models.IntegerField(default=1, verbose_name='Nombre de personnes')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total (FCFA)')),
                ('date_entree', models.DateTimeField(auto_now_add=True, verbose_name="Date d'entrée")),
                ('date_sortie', models.DateTimeField(blank=True, null=True, verbose_name='Date de sortie')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Accès piscine',
                'verbose_name_plural': 'Accès piscine',
                'ordering': ['-date_entree'],
            },
        ),
        migrations.CreateModel(
            name='ConsommationPiscine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100, verbose_name='Produit')),
                ('quantite', models.IntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('acces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='piscine.accespiscine', verbose_name='Accès')),
            ],
            options={
                'verbose_name': 'Consommation',
                'verbose_name_plural': 'Consommations',
            },
        ),
    ]
