# Generated by Django 6.0.2 on 2026-03-19 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consommationpiscine',
            options={},
        ),
        migrations.AddField(
            model_name='accespiscine',
            name='nb_adultes',
            field=models.IntegerField(default=1, verbose_name='Adultes'),
        ),
        migrations.AddField(
            model_name='accespiscine',
            name='nb_enfants',
            field=models.IntegerField(default=0, verbose_name='Enfants'),
        ),
        migrations.AddField(
            model_name='tarifpiscine',
            name='type_tarif',
            field=models.CharField(choices=[('adulte', 'Adulte'), ('enfant', 'Enfant')], default='adulte', max_length=10, verbose_name='Adulte/Enfant'),
        ),
        migrations.AlterField(
            model_name='accespiscine',
            name='date_entree',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accespiscine',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accespiscine',
            name='enregistre_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consommationpiscine',
            name='acces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='piscine.accespiscine'),
        ),
        migrations.AlterField(
            model_name='consommationpiscine',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consommationpiscine',
            name='produit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consommationpiscine',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tarifpiscine',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='tarifpiscine',
            name='type_client',
            field=models.CharField(choices=[('heberge', 'Hébergé'), ('visiteur', 'Visiteur')], max_length=20, verbose_name='Type client'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifpiscine',
            unique_together={('type_client', 'type_tarif')},
        ),
    ]
