# Generated by Django 6.0.2 on 2026-03-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscine', '0002_alter_consommationpiscine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accespiscine',
            options={'ordering': ['-date_entree'], 'verbose_name': 'Accès piscine'},
        ),
        migrations.AlterModelOptions(
            name='tarifpiscine',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tarifpiscine',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='accespiscine',
            name='nombre_personnes',
        ),
        migrations.AlterField(
            model_name='accespiscine',
            name='nb_adultes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accespiscine',
            name='nb_enfants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accespiscine',
            name='nom_client',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accespiscine',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accespiscine',
            name='type_client',
            field=models.CharField(choices=[('heberge', 'Hébergé'), ('visiteur', 'Visiteur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tarifpiscine',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarifpiscine',
            name='type_tarif',
            field=models.CharField(choices=[('adulte_visiteur', 'Adulte visiteur'), ('enfant_visiteur', 'Enfant visiteur'), ('adulte_heberge', 'Adulte hébergé'), ('enfant_heberge', 'Enfant hébergé')], max_length=30, unique=True),
        ),
        migrations.RemoveField(
            model_name='tarifpiscine',
            name='type_client',
        ),
    ]
