# Generated by Django 6.0.2 on 2026-03-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piscine', '0004_accespiscine_reservation_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accespiscine',
            name='reservation_hotel',
        ),
    ]
