# Generated by Django 6.0.2 on 2026-03-21 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_add_piscine_type_consommation'),
        ('piscine', '0004_accespiscine_reservation_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accespiscine',
            name='reservation_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acces_piscine', to='hotel.reservation', verbose_name='Réservation hôtel liée'),
        ),
    ]
