# Generated by Django 5.2 on 2026-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscine', '0010_accespiscine_nb_forfaits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accespiscine',
            name='prix_total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accespiscine',
            name='remise_montant',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Remise (montant)'),
        ),
        migrations.AlterField(
            model_name='consommationpiscine',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarifpiscine',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
