# Generated by Django 6.0.1 on 2026-01-27 18:04

from django.db import migrations

def seed_services(apps, schema_editor):
    Service = apps.get_model('facturation', 'Service')
    services = [
        "Hôtel",
        "Restaurant",
        "Bar",
        "Espaces Location",
    ]
    for service_name in services:
        Service.objects.get_or_create(nom=service_name)

class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_services),
    ]
