# Generated by Django 6.0.1 on 2026-01-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_seed_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avoir',
            name='facture_originale',
        ),
        migrations.AddField(
            model_name='avoir',
            name='facture_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs', to='facturation.facture'),
        ),
    ]
