# Generated by Django 6.0.1 on 2026-01-27 21:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_remove_avoir_facture_originale_avoir_facture_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='proforma',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
