# Generated by Django 6.0.1 on 2026-01-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0004_avoir_remise_facture_remise_proforma_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='ticket_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs', to='facturation.ticket'),
        ),
    ]
