# Generated by Django 6.0.1 on 2026-02-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0006_ticket_cree_par_ticket_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('moov_money', 'Moov Money'), ('mtn_money', 'MTN Mobile Money'), ('carte_bancaire', 'Carte Bancaire'), ('carte', 'Carte Bancaire'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('autre', 'Autre')], default='especes', max_length=50),
        ),
    ]
