# Generated by Django 6.0.2 on 2026-03-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0007_alter_ticket_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('moov_money', 'Moov Money'), ('mtn_money', 'MTN Mobile Money'), ('carte_bancaire', 'Carte Bancaire'), ('carte', 'Carte Bancaire'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('cave', 'Cave'), ('autre', 'Autre')], default='especes', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='module',
            field=models.CharField(choices=[('hotel', 'Hôtel'), ('restaurant', 'Restaurant'), ('caisse', 'Caisse'), ('piscine', 'Piscine'), ('cave', 'Cave'), ('autre', 'Autre')], max_length=20),
        ),
    ]
