# Generated by Django 6.0.2 on 2026-03-25 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0008_alter_ticket_mode_paiement_alter_ticket_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneavoir',
            name='designation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Désignation'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='designation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Désignation'),
        ),
        migrations.AddField(
            model_name='ligneproforma',
            name='designation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='ligneavoir',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturation.article'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturation.article'),
        ),
        migrations.AlterField(
            model_name='ligneproforma',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturation.article'),
        ),
    ]
