# Generated by Django 6.0.2 on 2026-03-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0009_ligneavoir_designation_lignefacture_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('validee', 'Validée'), ('refused', 'Refusé'), ('annulee', 'Annulée'), ('invoiced', 'Facturé'), ('convertie', 'Convertie')], default='draft', max_length=20),
        ),
    ]
