# Generated by Django 6.0.2 on 2026-03-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0010_alter_proforma_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='module',
            field=models.CharField(choices=[('hotel', 'Hôtel'), ('restaurant', 'Restaurant'), ('caisse', 'Caisse'), ('piscine', 'Piscine'), ('cave', 'Cave'), ('espace', 'Espaces Événementiels'), ('autre', 'Autre')], max_length=20),
        ),
    ]
