# Generated by Django 5.2 on 2026-05-21 11:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0011_alter_ticket_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoir',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepted', 'Accepté'), ('traitee', 'Traitée'), ('refunded', 'Remboursé'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('en_attente', 'En attente'), ('payee', 'Payée'), ('impayee', 'Impayée'), ('partielle', 'Part. payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('acceptee', 'Acceptée'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('convertie', 'Convertie')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
