# Generated by Django 5.2 on 2026-09-01 12:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0012_alter_avoir_statut_alter_facture_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoir',
            name='montant_tva',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='remise',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='sous_total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='taux_tva',
            field=models.DecimalField(decimal_places=3, default=Decimal('20.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_paye',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='sous_total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='taux_tva',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ligneavoir',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ligneavoir',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ligneavoir',
            name='taux_remise',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='taux_remise',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='ligneproforma',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ligneproforma',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ligneproforma',
            name='taux_remise',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='montant_tva',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='remise',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='sous_total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='taux_tva',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='montant_paye',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='montant_total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
