# Generated by Django 5.2 on 2026-09-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0013_alter_avoir_montant_tva_alter_avoir_remise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='montant_especes',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
