# Generated by Django 5.2 on 2026-09-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0017_ticket_facture_consolidee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignepaiement',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('mobile_money', 'Mobile Money'), ('carte_bancaire', 'Carte Bancaire'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('cave', 'Cave (consommation bar)'), ('autre', 'Autre')], max_length=30),
        ),
    ]
