# Generated by Django 5.2 on 2026-09-21 14:38
# Data migration : renommer les statuts anglais de l'Avoir en français

from django.db import migrations


def statuts_vers_fr(apps, schema_editor):
    Avoir = apps.get_model('facturation', 'Avoir')
    Avoir.objects.filter(statut='accepted').update(statut='accepte')
    Avoir.objects.filter(statut='refunded').update(statut='rembourse')


def statuts_vers_en(apps, schema_editor):
    """Rollback — remet les valeurs anglaises."""
    Avoir = apps.get_model('facturation', 'Avoir')
    Avoir.objects.filter(statut='accepte').update(statut='accepted')
    Avoir.objects.filter(statut='rembourse').update(statut='refunded')


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0018_lignepaiement_add_cave_mode'),
    ]

    operations = [
        migrations.RunPython(statuts_vers_fr, statuts_vers_en),
    ]
