# Generated by Django 5.2 on 2026-09-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0019_avoir_statuts_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoir',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('traitee', 'Traitée'), ('rembourse', 'Remboursé'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
