# Generated by Django 6.0.2 on 2026-03-05 23:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoissonBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la boisson')),
                ('image', models.ImageField(blank=True, null=True, upload_to='boissons/', verbose_name='Image de la boisson')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de Vente (FCFA)')),
                ('quantite_stock', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('seuil_alerte', models.IntegerField(default=10, verbose_name="Seuil d'alerte")),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible à la vente')),
            ],
            options={
                'verbose_name': 'Boisson (Bar)',
                'verbose_name_plural': 'Boissons (Bar)',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CategorieBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de Boisson',
                'verbose_name_plural': 'Catégories de Boissons',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStockBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée (Achat/Réception)'), ('sortie', 'Sortie (Vente)'), ('casse', 'Casse / Perte'), ('inventaire', "Ajustement d'inventaire")], max_length=20)),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mouvement de stock (Bar)',
                'verbose_name_plural': 'Mouvements de stock (Bar)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BonCommandeBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro du bon')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé au fournisseur'), ('recu', 'Reçu'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('date_commande', models.DateField(default=django.utils.timezone.now)),
                ('date_reception_prevue', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon de Commande (Bar)',
                'verbose_name_plural': 'Bons de Commande (Bar)',
                'ordering': ['-date_commande'],
            },
        ),
    ]
