# Generated by Django 6.0.2 on 2026-03-05 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bar', '0001_initial'),
        ('cuisine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommandebar',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.categoriebar', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='mouvementstockbar',
            name='boisson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='bar.boissonbar'),
        ),
        migrations.AddField(
            model_name='mouvementstockbar',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
