# Generated by Django 6.0.2 on 2026-03-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Numéro de table')),
                ('capacite', models.IntegerField(default=2, verbose_name='Capacité (personnes)')),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée'), ('reservee', 'Réservée')], default='libre', max_length=20, verbose_name='Statut')),
                ('zone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zone (Ex: Terrasse, Intérieur)')),
            ],
            options={
                'verbose_name': 'Table (Cave)',
                'verbose_name_plural': 'Tables (Cave)',
                'ordering': ['numero'],
            },
        ),
    ]
