# Generated by Django 6.0.2 on 2026-03-11 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_tablebar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'unité")),
                ('abreviation', models.CharField(blank=True, max_length=10, verbose_name='Abréviation')),
            ],
            options={
                'verbose_name': 'Unité de vente',
                'verbose_name_plural': 'Unités de vente',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='boissonbar',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Article (Cave)', 'verbose_name_plural': 'Articles (Cave)'},
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='est_compose',
            field=models.BooleanField(default=False, verbose_name='Article composé (pack/nomenclature)'),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='marge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Marge (%)'),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='mode_prix',
            field=models.CharField(choices=[('manuel', 'Prix saisi manuellement'), ('marge', 'Calculé (prix achat + marge %)')], default='manuel', max_length=10, verbose_name='Mode de calcul du prix'),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat (FCFA)"),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence article'),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('sommeil', 'En sommeil'), ('supprime', 'Supprimé')], default='actif', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='unite_standard',
            field=models.CharField(choices=[('bouteille', 'Bouteille'), ('verre', 'Verre'), ('cl', 'Cl'), ('litre', 'Litre'), ('autre', 'Autre (personnalisé)')], default='bouteille', max_length=20, verbose_name='Unité standard'),
        ),
        migrations.AlterField(
            model_name='boissonbar',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.categoriebar', verbose_name='Famille / Catégorie'),
        ),
        migrations.AlterField(
            model_name='boissonbar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boissons/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='boissonbar',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='boissonbar',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente (FCFA)'),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='unite_personnalisee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.unitevente', verbose_name='Unité personnalisée'),
        ),
    ]
