# Generated by Django 6.0.2 on 2026-03-11 21:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_unitevente_alter_boissonbar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom / Raison sociale')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('vip', 'VIP'), ('autre', 'Autre')], default='particulier', max_length=20, verbose_name='Type')),
                ('personne_contact', models.CharField(blank=True, max_length=200, verbose_name='Personne à contacter')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='boncommandebar',
            options={'ordering': ['-date_commande'], 'verbose_name': 'Bon de Commande (Cave)', 'verbose_name_plural': 'Bons de Commande (Cave)'},
        ),
        migrations.RemoveField(
            model_name='boncommandebar',
            name='date_reception_prevue',
        ),
        migrations.AddField(
            model_name='boncommandebar',
            name='date_livraison_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date livraison prévue'),
        ),
        migrations.AddField(
            model_name='boncommandebar',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='boncommandebar',
            name='date_reception_effective',
            field=models.DateField(blank=True, null=True, verbose_name='Date réception effective'),
        ),
        migrations.AddField(
            model_name='boncommandebar',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes / Observations'),
        ),
        migrations.AddField(
            model_name='boncommandebar',
            name='type_commande',
            field=models.CharField(choices=[('achat', 'Commande Fournisseur (Achat)'), ('vente', 'Commande Client (Vente)')], default='achat', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='boncommandebar',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_bar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boncommandebar',
            name='date_commande',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date commande'),
        ),
        migrations.AlterField(
            model_name='boncommandebar',
            name='numero',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='boncommandebar',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('envoye', 'Envoyé'), ('partiel', 'Partiel'), ('recu', 'Reçu'), ('livre', 'Livré'), ('facture', 'Facturé'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='boncommandebar',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.client', verbose_name='Client'),
        ),
        migrations.CreateModel(
            name='LigneBonCommandeBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qté commandée')),
                ('quantite_recue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qté reçue / livrée')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('notes_ligne', models.CharField(blank=True, max_length=200, verbose_name='Note ligne')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bar.boissonbar', verbose_name='Article')),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bar.boncommandebar')),
            ],
            options={
                'verbose_name': 'Ligne de bon de commande',
                'verbose_name_plural': 'Lignes de bons de commande',
            },
        ),
    ]
