# Generated by Django 6.0.2 on 2026-03-11 22:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_client_alter_boncommandebar_options_and_more'),
        ('cuisine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonReceptionBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('numero_document_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='N° document fournisseur (facture / BL)')),
                ('date_reception', models.DateField(default=django.utils.timezone.now, verbose_name='Date de réception')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='bar.boncommandebar', verbose_name='Bon de commande lié')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.fournisseur', verbose_name='Fournisseur')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions_bar', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_reception_bar', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Bon de Réception (Cave)',
                'verbose_name_plural': 'Bons de Réception (Cave)',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='LigneBonReceptionBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qté commandée (référence)')),
                ('quantite_recue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qté reçue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('notes_ligne', models.CharField(blank=True, max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bar.boissonbar', verbose_name='Article')),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bar.bonreceptionbar')),
            ],
            options={
                'verbose_name': 'Ligne de réception (Cave)',
                'verbose_name_plural': 'Lignes de réception (Cave)',
            },
        ),
    ]
