# Generated by Django 6.0.2 on 2026-03-11 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0006_bonreceptionbar_lignebonreceptionbar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventaireBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_bar', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_inventaire_bar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire (Cave)',
                'verbose_name_plural': 'Inventaires (Cave)',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaireBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qté théorique (système)')),
                ('quantite_comptee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qté comptée (physique)')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire')),
                ('notes_ligne', models.CharField(blank=True, max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bar.boissonbar')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bar.inventairebar')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire (Cave)",
                'unique_together': {('inventaire', 'article')},
            },
        ),
    ]
