# Generated by Django 6.0.2 on 2026-03-11 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0007_inventairebar_ligneinventairebar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasseBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('type_casse', models.CharField(choices=[('casse', 'Casse (bouteille brisée)'), ('perte', 'Perte / Gâchis'), ('perime', 'Produit périmé'), ('vol', 'Vol / Disparition'), ('offert', 'Offert / Dégustation'), ('autre', 'Autre')], default='casse', max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('declare', 'Déclaré'), ('valide', 'Validé'), ('annule', 'Annulé')], default='declare', max_length=20)),
                ('date_casse', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la casse')),
                ('description', models.TextField(blank=True, verbose_name='Description / Circonstances')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('declare_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casses_declarees_bar', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casses_validees_bar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Casse / Perte (Cave)',
                'verbose_name_plural': 'Casses / Pertes (Cave)',
                'ordering': ['-date_casse'],
            },
        ),
        migrations.CreateModel(
            name='LigneCasseBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité perdue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('notes_ligne', models.CharField(blank=True, max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bar.boissonbar')),
                ('casse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bar.cassebar')),
            ],
            options={
                'verbose_name': 'Ligne de casse',
                'verbose_name_plural': 'Lignes de casse',
            },
        ),
    ]
