# Generated by Django 5.2 on 2026-06-21 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_cassebar_lignecassebar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstockbar',
            name='serveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_bar', to=settings.AUTH_USER_MODEL, verbose_name='Serveur/Serveuse'),
        ),
        migrations.AlterField(
            model_name='mouvementstockbar',
            name='type_mouvement',
            field=models.CharField(choices=[('entree', 'Entrée (Achat/Réception)'), ('sortie', 'Sortie (Vente)'), ('casse', 'Casse / Perte'), ('inventaire_excedent', 'Inventaire — Excédent'), ('inventaire_manquant', 'Inventaire — Manquant'), ('inventaire', 'Inventaire — Conforme')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mouvementstockbar',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_bar', to=settings.AUTH_USER_MODEL),
        ),
    ]
