# Generated by Django 5.2 on 2026-06-22 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0009_serveur_mouvement_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FournisseurBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('type_fournisseur', models.CharField(choices=[('grossiste', 'Grossiste'), ('producteur', 'Producteur / Importateur'), ('importateur', 'Importateur'), ('distributeur', 'Distributeur'), ('autre', 'Autre')], default='grossiste', max_length=20, verbose_name='Type')),
                ('personne_contact', models.CharField(blank=True, max_length=200, verbose_name='Contact')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('telephone2', models.CharField(blank=True, max_length=20, verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Fournisseur (Cave)',
                'verbose_name_plural': 'Fournisseurs (Cave)',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='boncommandebar',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.fournisseurbar', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='bonreceptionbar',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.fournisseurbar', verbose_name='Fournisseur'),
        ),
    ]
