# Generated by Django 5.2 on 2026-06-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0010_fournisseurbar'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE bar_inventairebar SET statut='brouillon' WHERE statut='en_cours';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='inventairebar',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
    ]
