# Generated by Django 5.2 on 2026-06-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0011_inventaire_remove_en_cours_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneinventairebar',
            name='prix_unitaire',
        ),
        migrations.AddField(
            model_name='ligneinventairebar',
            name='valeur_ecart',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur écart (FCFA)'),
        ),
    ]
