# Generated by Django 5.2 on 2026-07-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0012_valeur_ecart_inventaire_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boissonbar',
            name='unite_standard',
            field=models.CharField(choices=[('bouteille', 'Bouteille'), ('canette', 'Canette'), ('verre', 'Verre'), ('cl', 'Cl'), ('litre', 'Litre'), ('autre', 'Autre (personnalisé)')], default='bouteille', max_length=20, verbose_name='Unité standard'),
        ),
    ]
