# Generated by Django 5.2 on 2026-08-22 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0013_add_canette_unite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrageShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_contenant_ml', models.IntegerField(default=700, help_text='Ex: 700 pour une bouteille 70cl', verbose_name='Volume du contenant (ml)')),
                ('volume_shot_ml', models.IntegerField(default=30, verbose_name="Volume d'un shot (ml)")),
                ('prix_shot', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix du shot (FCFA)')),
                ('prix_tournee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de la tournée (2 shots, FCFA)')),
                ('ml_en_cours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ml consommés (bouteille en cours)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('boisson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametrage_shot', to='bar.boissonbar', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Paramétrage Shot',
                'verbose_name_plural': 'Paramétrages Shot',
            },
        ),
        migrations.CreateModel(
            name='VenteShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vente', models.CharField(choices=[('shot', 'Shot (1 verre)'), ('tournee', 'Tournée (2 shots)')], default='shot', max_length=10)),
                ('nb_shots', models.IntegerField(default=1, verbose_name='Nombre de shots')),
                ('ml_debites', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ml débités')),
                ('prix_encaisse', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix encaissé (FCFA)')),
                ('commentaire', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('boisson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_shot', to='bar.boissonbar')),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_shot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente Shot',
                'verbose_name_plural': 'Ventes Shot',
                'ordering': ['-date'],
            },
        ),
    ]
