# Generated by Django 5.2 on 2026-08-22 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0014_add_parametrage_shot_vente_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='boissonbar',
            name='est_shot',
            field=models.BooleanField(default=False, verbose_name="Article shot (dérivé d'une bouteille)"),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='shot_ml',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume en ml (si shot dérivé)'),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='shot_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_shot', to='bar.boissonbar', verbose_name='Bouteille parente (si shot dérivé)'),
        ),
        migrations.AddField(
            model_name='parametrageshot',
            name='article_shot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_shot_source', to='bar.boissonbar', verbose_name='Article shot (auto-créé)'),
        ),
        migrations.AddField(
            model_name='parametrageshot',
            name='article_tournee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_tournee_source', to='bar.boissonbar', verbose_name='Article tournée (auto-créé)'),
        ),
    ]
