# Generated by Django 5.2 on 2026-08-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0019_glace_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='boissonbar',
            name='ingredient_secondaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_utilisant', to='bar.boissonbar', verbose_name='Ingrédient secondaire (débité automatiquement)'),
        ),
        migrations.AddField(
            model_name='boissonbar',
            name='quantite_secondaire',
            field=models.IntegerField(default=1, verbose_name='Quantité débitée par vente'),
        ),
    ]
