# Generated by Django 5.2 on 2026-08-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0024_boissonbar_cmup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boissonbar',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Dernier prix d'achat (FCFA)"),
        ),
    ]
