# Generated by Django 5.2 on 2026-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0025_alter_boissonbar_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boissonbar',
            name='marge',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Marge (%)'),
        ),
        migrations.AlterField(
            model_name='boissonbar',
            name='prix',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Prix de vente (FCFA)'),
        ),
        migrations.AlterField(
            model_name='boissonbar',
            name='prix_achat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name="Dernier prix d'achat (FCFA)"),
        ),
        migrations.AlterField(
            model_name='ligneboncommandebar',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix unitaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='ligneboncommandebar',
            name='quantite_commandee',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Qté commandée'),
        ),
        migrations.AlterField(
            model_name='ligneboncommandebar',
            name='quantite_recue',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Qté reçue / livrée'),
        ),
        migrations.AlterField(
            model_name='lignebonreceptionbar',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix unitaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='lignebonreceptionbar',
            name='quantite_commandee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Qté commandée (référence)'),
        ),
        migrations.AlterField(
            model_name='lignebonreceptionbar',
            name='quantite_recue',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Qté reçue'),
        ),
        migrations.AlterField(
            model_name='lignecassebar',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Prix unitaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='lignecassebar',
            name='quantite',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité perdue'),
        ),
        migrations.AlterField(
            model_name='ligneinventairebar',
            name='quantite_comptee',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Qté comptée (physique)'),
        ),
        migrations.AlterField(
            model_name='ligneinventairebar',
            name='quantite_theorique',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Qté théorique (système)'),
        ),
        migrations.AlterField(
            model_name='ligneinventairebar',
            name='valeur_ecart',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Valeur écart (FCFA)'),
        ),
        migrations.AlterField(
            model_name='ligneventecave',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrageshot',
            name='ml_en_cours',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='ml consommés (bouteille en cours)'),
        ),
        migrations.AlterField(
            model_name='parametrageshot',
            name='prix_shot',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Prix du shot (FCFA)'),
        ),
        migrations.AlterField(
            model_name='parametrageshot',
            name='prix_tournee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Prix de la tournée (2 shots, FCFA)'),
        ),
        migrations.AlterField(
            model_name='ventecave',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venteshot',
            name='ml_debites',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='ml débités'),
        ),
        migrations.AlterField(
            model_name='venteshot',
            name='prix_encaisse',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix encaissé (FCFA)'),
        ),
    ]
