# Generated by Django 5.2 on 2026-09-08 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0028_parametrageshot_ml_ouverts_ouverture_contenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventairebar',
            name='date_inventaire',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'inventaire"),
        ),
        migrations.AddField(
            model_name='inventairebar',
            name='motif_inventaire',
            field=models.CharField(choices=[('periodique', 'Inventaire périodique'), ('annuel', 'Inventaire annuel'), ('surprise', 'Contrôle surprise'), ('arrete', 'Arrêté comptable'), ('reception', 'Suite réception'), ('autre', 'Autre')], default='periodique', max_length=20, verbose_name='Motif'),
        ),
        migrations.AddField(
            model_name='ligneinventairebar',
            name='cmup_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='CMUP au moment de la validation'),
        ),
    ]
