# Generated by Django 6.0.1 on 2026-01-21 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_evenement', models.DateField(verbose_name="Date de l'événement")),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('prix_entree', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'entrée (FCFA)")),
                ('capacite_max', models.IntegerField(blank=True, null=True, verbose_name='Capacité maximale')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_evenement'],
            },
        ),
        migrations.CreateModel(
            name='TableBoite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Numéro')),
                ('type_table', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP')], max_length=20, verbose_name='Type')),
                ('capacite', models.IntegerField(verbose_name='Capacité (personnes)')),
                ('prix_reservation', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix réservation (FCFA)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupee', 'Occupée'), ('reservee', 'Réservée')], default='disponible', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='EntreeBoite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('nombre_personnes', models.IntegerField(default=1, verbose_name='Nombre de personnes')),
                ('prix_entree', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'entrée (FCFA)")),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boite_nuit.evenement', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Entrée',
                'verbose_name_plural': 'Entrées',
                'ordering': ['-date_entree'],
            },
        ),
        migrations.CreateModel(
            name='ConsommationBoite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du client')),
                ('produit', models.CharField(max_length=100, verbose_name='Produit')),
                ('quantite', models.IntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('serveur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Serveur')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boite_nuit.tableboite', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Consommation',
                'verbose_name_plural': 'Consommations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
