# Generated by Django 5.2 on 2026-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_nuit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommationboite',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix unitaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='consommationboite',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Total (FCFA)'),
        ),
        migrations.AlterField(
            model_name='entreeboite',
            name='prix_entree',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name="Prix d'entrée (FCFA)"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='prix_entree',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name="Prix d'entrée (FCFA)"),
        ),
        migrations.AlterField(
            model_name='tableboite',
            name='prix_reservation',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Prix réservation (FCFA)'),
        ),
    ]
