# Generated by Django 6.0.2 on 2026-03-05 23:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0006_alter_platmenu_prix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': "Catégorie d'article",
                'verbose_name_plural': "Catégories d'articles",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'emplacement")),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom du fournisseur')),
                ('personne_contact', models.CharField(blank=True, max_length=200, verbose_name='Personne à contacter')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name="Nom de l'unité")),
                ('abreviation', models.CharField(max_length=10, unique=True, verbose_name='Abréviation')),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FicheTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_portions', models.IntegerField(default=1, verbose_name='Nombre de portions')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions de préparation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fiches_techniques/', verbose_name='Image du plat')),
                ('marge_souhaitee', models.DecimalField(decimal_places=2, default=70, help_text='Pourcentage de marge pour calculer le prix de vente suggéré.', max_digits=5, verbose_name='Marge souhaitée (%)')),
                ('temps_preparation', models.IntegerField(default=0, verbose_name='Temps de préparation (min)')),
                ('temps_cuisson', models.IntegerField(default=0, verbose_name='Temps de cuisson (min)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('plat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_technique', to='restaurant.platmenu', verbose_name='Plat associé')),
            ],
            options={
                'verbose_name': 'Fiche Technique',
                'verbose_name_plural': 'Fiches Techniques',
            },
        ),
        migrations.CreateModel(
            name='BonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_document', models.CharField(blank=True, help_text='N° de facture ou de bon de livraison', max_length=50, null=True)),
                ('date_reception', models.DateField(default=django.utils.timezone.now)),
                ('etat', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_cours', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_reception', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de Réception',
                'verbose_name_plural': 'Bons de Réception',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'article")),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code Article')),
                ('quantite_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantité en stock')),
                ('seuil_alerte', models.DecimalField(decimal_places=3, default=5, max_digits=10, verbose_name='Stock Minimum')),
                ('prix_moyen', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="CMUP (Prix d'achat)")),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='cuisine.categorieingredient', verbose_name='Catégorie')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.emplacement', verbose_name='Emplacement')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.unite', verbose_name='Unité de mesure')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneBonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, help_text="Prix d'achat unitaire pour cette livraison", max_digits=10)),
                ('bon_reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='cuisine.bonreception')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.ingredient')),
            ],
            options={
                'verbose_name': 'Ligne de Bon de Réception',
                'verbose_name_plural': 'Lignes des Bons de Réception',
            },
        ),
        migrations.CreateModel(
            name='LigneFicheTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité nécessaire')),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de Vente Spécifique')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='cuisine.fichetechnique')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.ingredient', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Ligne fiche technique',
                'verbose_name_plural': 'Lignes fiche technique',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée (Achat)'), ('sortie', 'Sortie (Utilisation)'), ('perte', 'Perte / Gâchis'), ('prelevement', 'Prélèvement Propriétaire'), ('inventaire', 'Ajustement Inventaire')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire (si achat)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.fournisseur', verbose_name='Fournisseur')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='cuisine.ingredient')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
    ]
