# Generated by Django 6.0.2 on 2026-03-12 00:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('icone', models.CharField(blank=True, default='fa-utensils', max_length=50, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Catégorie de plat',
                'verbose_name_plural': 'Catégories de plats',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='UniteIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'unité")),
                ('abreviation', models.CharField(blank=True, max_length=10, verbose_name='Abréviation')),
                ('type_unite', models.CharField(choices=[('masse', 'Masse (kg, g...)'), ('volume', 'Volume (L, cl, ml...)'), ('piece', 'Pièce / unité'), ('autre', 'Autre')], default='piece', max_length=20, verbose_name="Type d'unité")),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='lignebonreception',
            name='bon_reception',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='emplacement',
        ),
        migrations.RemoveField(
            model_name='lignebonreception',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unite',
        ),
        migrations.AlterModelOptions(
            name='categorieingredient',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': "Catégorie d'ingrédient", 'verbose_name_plural': "Catégories d'ingrédients"},
        ),
        migrations.AlterModelOptions(
            name='fichetechnique',
            options={'ordering': ['categorie__ordre', 'nom'], 'verbose_name': 'Fiche Technique', 'verbose_name_plural': 'Fiches Techniques'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['categorie__ordre', 'nom'], 'verbose_name': 'Ingrédient', 'verbose_name_plural': 'Ingrédients'},
        ),
        migrations.AlterModelOptions(
            name='lignefichetechnique',
            options={'ordering': ['id'], 'verbose_name': 'Ligne de fiche technique', 'verbose_name_plural': 'Lignes de fiches techniques'},
        ),
        migrations.RemoveField(
            model_name='fichetechnique',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='fichetechnique',
            name='marge_souhaitee',
        ),
        migrations.RemoveField(
            model_name='fichetechnique',
            name='nombre_portions',
        ),
        migrations.RemoveField(
            model_name='fichetechnique',
            name='plat',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='prix_moyen',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='prix_vente',
        ),
        migrations.RemoveField(
            model_name='lignefichetechnique',
            name='prix_vente',
        ),
        migrations.AddField(
            model_name='categorieingredient',
            name='icone',
            field=models.CharField(blank=True, default='fa-box', max_length=50, verbose_name='Icône FontAwesome'),
        ),
        migrations.AddField(
            model_name='categorieingredient',
            name='ordre',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_techniques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description / Méthode'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='nb_portions',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=6, verbose_name='Nombre de portions'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='nom',
            field=models.CharField(default='', max_length=200, verbose_name='Nom de la recette'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='statut',
            field=models.CharField(choices=[('actif', 'Active'), ('archive', 'Archivée'), ('brouillon', 'Brouillon')], default='actif', max_length=20),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='telephone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone 2'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='type_fournisseur',
            field=models.CharField(choices=[('grossiste', 'Grossiste'), ('producteur', 'Producteur / Agriculteur'), ('importateur', 'Importateur'), ('distributeur', 'Distributeur'), ('autre', 'Autre')], default='grossiste', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cmup',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='CMUP (FCFA)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='facteur_conversion',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Ex : 1 kg = 1000 g → saisir 1000', max_digits=12, verbose_name='Facteur conversion stock→recette'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fournisseur_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.fournisseur', verbose_name='Fournisseur principal'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat unitaire (FCFA)"),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='statut',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='stock_max',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, verbose_name='Stock maximum'),
        ),
        migrations.AddField(
            model_name='lignefichetechnique',
            name='notes_ligne',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note (ex: haché, émincé...)'),
        ),
        migrations.AlterField(
            model_name='categorieingredient',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fiches_techniques/'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='personne_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.categorieingredient', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantite_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantité en stock'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='seuil_alerte',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name="Seuil d'alerte"),
        ),
        migrations.AlterField(
            model_name='lignefichetechnique',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.ingredient', verbose_name='Ingrédient'),
        ),
        migrations.AlterField(
            model_name='lignefichetechnique',
            name='quantite',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité (unité recette)'),
        ),
        migrations.CreateModel(
            name='BonCommandeCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('envoye', 'Envoyé au fournisseur'), ('partiel', 'Reçu partiellement'), ('recu', 'Reçu'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('date_commande', models.DateField(default=django.utils.timezone.now, verbose_name='Date commande')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True, verbose_name='Date livraison prévue')),
                ('date_reception_effective', models.DateField(blank=True, null=True, verbose_name='Date réception effective')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_cuisine', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de Commande (Cuisine)',
                'verbose_name_plural': 'Bons de Commande (Cuisine)',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='BonReceptionCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('date_reception', models.DateField(default=django.utils.timezone.now, verbose_name='Date de réception')),
                ('notes', models.TextField(blank=True, verbose_name='Observations / Écarts')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.boncommandecuisine', verbose_name='Bon de commande lié')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_cuisine', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.fournisseur', verbose_name='Fournisseur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_cuisine_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon de Réception (Cuisine)',
                'verbose_name_plural': 'Bons de Réception (Cuisine)',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='CasseCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('type_casse', models.CharField(choices=[('casse', 'Casse / Bris'), ('perime', 'Périmé'), ('perte', 'Perte / Coulage'), ('vol', 'Vol'), ('offert', 'Offert / Dégustation'), ('autre', 'Autre')], default='casse', max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('declare', 'Déclaré'), ('valide', 'Validé — déduit du stock'), ('annule', 'Annulé')], default='declare', max_length=20)),
                ('date_casse', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description / Circonstances')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casses_cuisine', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casses_cuisine_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Déclaration de casse (Cuisine)',
                'verbose_name_plural': 'Déclarations de casse (Cuisine)',
                'ordering': ['-date_casse'],
            },
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.categorieplat', verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='InventaireCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('date_inventaire', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'inventaire")),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_cuisine', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_cuisine_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire (Cuisine)',
                'verbose_name_plural': 'Inventaires (Cuisine)',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.CreateModel(
            name='LigneBonCommandeCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Qté commandée')),
                ('quantite_recue', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Qté reçue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('notes_ligne', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='cuisine.boncommandecuisine')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.ingredient', verbose_name='Ingrédient')),
            ],
            options={
                'verbose_name': 'Ligne de BC (Cuisine)',
                'verbose_name_plural': 'Lignes de BC (Cuisine)',
            },
        ),
        migrations.CreateModel(
            name='LigneBonReceptionCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recue', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Qté reçue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('notes_ligne', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='cuisine.bonreceptioncuisine')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.ingredient', verbose_name='Ingrédient')),
            ],
            options={
                'verbose_name': 'Ligne de BR (Cuisine)',
                'verbose_name_plural': 'Lignes de BR (Cuisine)',
            },
        ),
        migrations.CreateModel(
            name='LigneCasseCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('notes_ligne', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('casse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='cuisine.cassecuisine')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.ingredient', verbose_name='Ingrédient')),
            ],
            options={
                'verbose_name': 'Ligne de casse (Cuisine)',
                'verbose_name_plural': 'Lignes de casse (Cuisine)',
            },
        ),
        migrations.CreateModel(
            name='LigneInventaireCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Qté théorique (stock)')),
                ('quantite_physique', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Qté physique (comptée)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.ingredient', verbose_name='Ingrédient')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='cuisine.inventairecuisine')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire (Cuisine)",
                'verbose_name_plural': "Lignes d'inventaire (Cuisine)",
            },
        ),
        migrations.CreateModel(
            name='MouvementStockCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée (Réception)'), ('sortie', 'Sortie (Consommation)'), ('casse', 'Casse / Perte'), ('inventaire', "Ajustement d'inventaire"), ('production', 'Consommation production')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Prix unitaire')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='cuisine.ingredient')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock (Cuisine)',
                'verbose_name_plural': 'Mouvements de stock (Cuisine)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du plat')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence')),
                ('description_carte', models.TextField(blank=True, verbose_name='Description pour la carte client')),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente (FCFA)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible (rupture)'), ('saisonnier', 'Saisonnier'), ('archive', 'Archivé')], default='disponible', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plats/')),
                ('ordre_carte', models.IntegerField(default=0, verbose_name='Ordre sur la carte')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.categorieplat', verbose_name='Catégorie')),
                ('fiche_technique', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plat', to='cuisine.fichetechnique', verbose_name='Fiche Technique liée')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['categorie__ordre', 'ordre_carte', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unite_recette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients_recette', to='cuisine.uniteingredient', verbose_name='Unité recette (fiches techniques)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unite_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients_stock', to='cuisine.uniteingredient', verbose_name='Unité de stock'),
        ),
        migrations.DeleteModel(
            name='BonReception',
        ),
        migrations.DeleteModel(
            name='Emplacement',
        ),
        migrations.DeleteModel(
            name='LigneBonReception',
        ),
        migrations.DeleteModel(
            name='MouvementStock',
        ),
        migrations.DeleteModel(
            name='Unite',
        ),
    ]
