# Generated by Django 5.2 on 2026-06-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_categorieplat_uniteingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstockcuisine',
            name='type_mouvement',
            field=models.CharField(choices=[('entree', 'Entrée (Réception)'), ('sortie', 'Sortie (Consommation)'), ('casse', 'Casse / Perte'), ('production', 'Consommation production'), ('inventaire_excedent', 'Inventaire — Excédent'), ('inventaire_manquant', 'Inventaire — Manquant'), ('inventaire', 'Inventaire — Conforme')], max_length=30),
        ),
    ]
