# Generated by Django 5.2 on 2026-06-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0003_alter_mouvementstockcuisine_type_mouvement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ligneinventairecuisine',
            unique_together={('inventaire', 'ingredient')},
        ),
    ]
