# Generated by Django 5.2 on 2026-06-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0004_unique_ligne_inventaire_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventairecuisine',
            name='valeur_ecart',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur écart (FCFA)'),
        ),
    ]
