# Generated by Django 5.2 on 2026-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0005_valeur_ecart_inventaire_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventairecuisine',
            name='notes_ligne',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note'),
        ),
    ]
