# Generated by Django 5.2 on 2026-08-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0007_alter_mouvementstockcuisine_type_mouvement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='facteur_conversion',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Ex : 5 Bananes = 1 Portion Alloco → saisir 5', max_digits=12, verbose_name='Quantité stock par unité recette'),
        ),
    ]
