# Generated by Django 5.2 on 2026-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0015_add_unites_manquantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='prix_achat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name="Prix d'achat unitaire (FCFA)"),
        ),
        migrations.AlterField(
            model_name='ligneboncommandecuisine',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix unitaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='lignebonreceptioncuisine',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix unitaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='ligneinventairecuisine',
            name='valeur_ecart',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Valeur écart (FCFA)'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='prix_vente',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Prix de vente (FCFA)'),
        ),
    ]
