# Generated by Django 5.2 on 2026-09-03 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0016_alter_ingredient_prix_achat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventairecuisine',
            name='inventaire_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='cuisine.inventairecuisine', verbose_name='Correction de'),
        ),
        migrations.AddField(
            model_name='inventairecuisine',
            name='type_inventaire',
            field=models.CharField(choices=[('complet', 'Inventaire complet'), ('partiel', 'Inventaire partiel'), ('correction', 'Correction')], default='complet', max_length=20, verbose_name='Type'),
        ),
    ]
