# Generated by Django 5.2 on 2026-09-03 00:56

from django.db import migrations, models


def marquer_lignes_existantes_comme_comptees(apps, schema_editor):
    LigneInventaireCuisine = apps.get_model('cuisine', 'LigneInventaireCuisine')
    LigneInventaireCuisine.objects.all().update(statut='compte')


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0017_inventaire_type_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventairecuisine',
            name='statut',
            field=models.CharField(choices=[('a_compter', 'À compter'), ('compte', 'Compté'), ('confirme_zero', 'Confirmé à zéro')], default='a_compter', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ligneinventairecuisine',
            name='quantite_physique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Qté physique (comptée)'),
        ),
        migrations.RunPython(marquer_lignes_existantes_comme_comptees, migrations.RunPython.noop),
    ]
