# Generated by Django 5.2 on 2026-09-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0018_ligne_inventaire_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventairecuisine',
            name='motif_inventaire',
            field=models.CharField(choices=[('periodique', 'Inventaire périodique'), ('annuel', 'Inventaire annuel'), ('surprise', 'Contrôle surprise'), ('arrete', 'Arrêté comptable'), ('reception', 'Suite réception'), ('autre', 'Autre')], default='periodique', max_length=20, verbose_name='Motif'),
        ),
        migrations.AddField(
            model_name='ligneinventairecuisine',
            name='cmup_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='CMUP au moment de la validation'),
        ),
    ]
